apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: workshop
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: workshop
roleRef:
  kind: Role
  name: app-role 
  apiGroup: rbac.authorization.k8s.io